name: Bug Report
description: Create a report with a procedure for reproducing the bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your Environment
      description: |
        - Firefox version:
        - IE View WE addon version: See about:addons.

        Tip: If you hit the problem with older IE View WE version, try latest version first.
      value: |
        - Firefox version:
        - IE View WE Firefox addon version:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Your Configuration
      description: |
        Write your IE View WE configuration. Minimum reproducible one is recommended.
      value: |
        - Force IE list:
        - Sites opened by self:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Your debug log
      description: Write your debug log here
      render: shell
    validations:
      required: false
  - type: textarea
    id: addtional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
